---
# site.yml
- name: Install Clickhouse
  hosts: clickhouse
  # gather_facts: false
  roles:
    - role: clickhouse
      tags: clickhouse

- name: Install Vector
  hosts: vector
  handlers:
    - name: Start Vector service
      become: true
      ansible.builtin.service:
        name: vector
        state: restarted
  roles:
    - vector-role

- name: Install Lighthouse
  hosts: lighthouse
  gather_facts: false
  roles:
    - role: lighthouse-role
      tags: lighthouse