# vector_config.yml
vector_config:
  # Vector configuration here
  sources:
    [sources.my_source]
      type = "stdin"

  sinks:
    [sinks.my_sink]
      type = "stdout"

  transforms:
    [transforms.my_transform]
      type = "remove_fields"
      fields = ["field_to_remove"]

  pipelines:
    [pipelines.my_pipeline]
      input = "my_source"
      output = "my_sink"
      transforms = ["my_transform"]
